import {
  AddressValidator,
  AttachmentValidator,
  CodeableConceptValidator,
  CodingValidator,
  ContactPointValidator,
  ElementValidator,
  ExtensionValidator,
  HumanNameValidator,
  IdentifierValidator,
  MetaValidator,
  NarrativeValidator,
  PeriodValidator,
  QuantityValidator,
  ReferenceValidator,
  RepeatValidator,
  ResourceValidator,
  AnnotationValidator,
  DurationValidator,
  RangeValidator,
  SimpleQuantityValidator,
} from '../datatypes';

export const InternalDataTypeValidator = {
  Period: PeriodValidator,
  Address: AddressValidator,
  Attachment: AttachmentValidator,
  Resource: ResourceValidator,
  CodeableConcept: CodeableConceptValidator,
  Coding: CodingValidator,
  HumanName: HumanNameValidator,
  Element: ElementValidator,
  Extension: ExtensionValidator,
  ContactPoint: ContactPointValidator,
  Identifier: IdentifierValidator,
  Reference: ReferenceValidator,
  Meta: MetaValidator,
  Narrative: NarrativeValidator,
  Quantity: QuantityValidator,
  Annotation: AnnotationValidator,
  Repeat: RepeatValidator,
  Duration: DurationValidator,
  Range: RangeValidator,
  SimpleQuantity: SimpleQuantityValidator,
};
